JD-1455 to master
mailru/jira-plugins-jsincluder pull request #47
Opened 2021-04-20 13:00 UTC by Bezneima

add console.log executed script name

2021-04-21 07:23 UTC, mashintsev requested changes

2021-04-21 07:23 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/controller-general.js
>      _executeJs: function(scripts) {
для _executeCss сделать аналогично

2021-04-21 07:23 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/controller-general.js
> +                    if (scripts[i].name)
проверка не нужна

2021-04-21 07:23 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/controller-general.js
> +                        console.log("JsIncluder execute script:", scripts[i].name);
Поменять текст на
"[JsIncluder] execute "  + scripts[i].name

2021-04-21 11:14 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/jsincluder/controller-general.js
>      _executeJs: function(scripts) {
Сделал

2021-04-21 11:14 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/jsincluder/controller-general.js
> +                    if (scripts[i].name)
Убрал

2021-04-21 11:14 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/jsincluder/controller-general.js
> +                        console.log("JsIncluder execute script:", scripts[i].name);
Изменил

2021-04-22 07:25 UTC, mashintsev requested changes

2021-04-22 07:25 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/controller-general.js
> +                console.log('[%cJsIncluder%c] apply css '+scripts[i].name,'color: #bada55','color:#bec6cf');
форматирование кривое

2021-04-22 07:25 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/controller-general.js
> +                    console.log('[%cJsIncluder%c] execute '+scripts[i].name,'color: #bada55','color:#bec6cf');
форматирование кривое

2021-04-23 08:52 UTC, merged