add js/css code validation
mailru/jira-plugins-jsincluder pull request #54
Opened 2021-07-19 21:28 UTC by Bezneima

2021-07-20 05:14 UTC, mashintsev requested changes

2021-07-20 05:14 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/configuration/configuration-dialog.js
> +                        clearTimeout(waiting);
бесполезный вызов, waiting выше не инициализирован.

2021-07-20 05:14 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/configuration/configuration-dialog.js
> +                        waiting = setTimeout(_updateHints, 500);
нужно что-то другое использовать взамен setTimeout. Может по события keyup, keydown или еще что-то

2021-07-20 12:12 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/jsincluder/configuration/configuration-dialog.js
> +                        clearTimeout(waiting);
Поменял на underscore.debounce

2021-07-20 12:13 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/jsincluder/configuration/configuration-dialog.js
> +                        waiting = setTimeout(_updateHints, 500);
Поменял на underscore.debounce

2021-07-20 12:17 UTC, mashintsev requested changes

2021-07-20 12:17 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/configuration/configuration-dialog.js
> +                _.debounce(_updateHints,100)();
debounce версию нужно один раз создать выше и потом ее просто вызывать в нужных местах

2021-07-20 13:02 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/jsincluder/configuration/configuration-dialog.js
> +                _.debounce(_updateHints,100)();
Вынес

2021-07-21 14:28 UTC, mashintsev approved these changes

2021-07-21 14:28 UTC, merged