JD-1703 to master
mailru/jira-plugins-jsincluder pull request #60
Opened 2021-09-03 11:55 UTC by Bezneima

Take values for filter selections from a set of scripts

2021-09-07 21:19 UTC, mashintsev requested changes

2021-09-07 21:19 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/jsincluder/configuration/configuration-page.js
> +            formatFilterOption(state) {
эта функция не используется, нужно удалить

2021-09-07 21:29 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/jsincluder/configuration/configuration-page.js
> +            formatFilterOption(state) {
Удалил

2021-09-08 08:07 UTC, mashintsev approved these changes

2021-09-08 08:07 UTC, merged